version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Update dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install --dev
      - run:
          name: Run Tests
          command: bash setup/prod_tests.sh
workflows:
  version: 2
  workflow:
    jobs:
    - build
